version: "3.8"
services:
  api:
    container_name: api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - type: bind
        source: ./settings
        target: /app/settings
      - type: bind
        source: ./results
        target: /app/results
